### PR TITLE
Setting up Hexo for documentation

### PR DESCRIPTION
**Pull request by muskankhedia**
Solves: #1 

**The parts covered in this PR:**
- Setting up Hexo as a dependency and added an npm script to generate docs
- setting up a reasonable _config.yml to deploy the docs
- setting up Travis to build and host docs via gh-pages

_The working is explained in the gif below:_
ezgif com-video-to-gif (1)

Note: For a check, the docs have been hosted in my account using the gh-pages branch. Pls, do update the `$GITHUB_TOKEN` for the proper and easy deployment of the docs in the organization GitHub link.

### CODE REVIEW

**Comment by muskankhedia** [comment]
@abhishek97 @championswimmer Pls have a view and suggest if any changes required.

**Comment by abhishek97** [comment]
how do i build the docs locally?, 
`./node_modules/.bin/hexo generate` inside `docs/` dir generate blank pages inside `docs/public`

**Comment by muskankhedia** [comment]
In order to generate the public folder and host it, create a branch named **gh-pages** in the repository with all the files and hexo installed,
then run the command <code>hexo clean && hexo deploy </code>. It will automatically host the github page with the docs in the link <code>https://org-name.github.io/express-jsonapi-controller/</code>. And then make any further changes in the master folder and deploy it, it will change in the gh-pages site.

**Comment by abhishek97** [comment]
@muskankhedia there should be a way to build docs locally as well.

**Comment by muskankhedia** [comment]
@abhishek97 yes you can view the docs locally in the by executing the command <code>hexo server</code> in that particular branch itself. It will be hosted in the local server `http://localhost:4000/`

**Comment by muskankhedia** [comment]
As now once the complete doc has been set up, anyone can easily deploy the changes and add more files in the future. This will make the work a lot easier in the future.

**Comment by muskankhedia** [comment]
@abhishek97 Pls have a look in the PR.

**Comment by abhishek97** [comment]
@muskankhedia I get empty response after running `hexo server`

**Comment by muskankhedia** [comment]
> @muskankhedia I get empty response after running `hexo server`
> Hit me up of Gitter, let's discuss this

Yaa sure.

**Pull request closed without merging**
