### PR TITLE
Setup Hexo for documentation

### PR DESCRIPTION
**Pull request by fluctix**
Solves #1 
Capturefdsfdg
(Uses Hexo Docs Theme)

### CODE REVIEW

**Comment by theParadoxicalWizard** [comment]
@abhishek97 Please review...I guess it should work fine now..

**Comment by abhishek97** [comment]
@theParadoxicalWizard Have you `hexo init` ? I don't think this would work either. Have you run it on your machine?

**Comment by theParadoxicalWizard** [comment]
Yes I have run it on my local system and it works , though if I had used
hexo init then we would have another package.json and thus another node
modules folder in the documentation folder , this is more viable

**Comment by theParadoxicalWizard** [comment]
@abhishek97 please review..

**Comment by abhishek97** [comment]
ignore `public/*` files. You need to correctly add hexo as dep inside package.json (use yarn add --dev hexo-cli) 
Event after that, this

```
SyntaxError: Unexpected token ] in JSON at position 558
    at JSON.parse (<anonymous>)
    at Hexo.jsonRenderer (/Users/abhishek/cb/express-jsonapi-controller/node_modules/hexo/lib/plugins/renderer/json.js:4:15)
    at Hexo.tryCatcher (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/abhishek/cb/express-jsonapi-controller/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/abhishek/cb/express-jsonapi-controller/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by theParadoxicalWizard** [comment]
@abhishek97 Wonder what might be causing it...It is working fine on my PC , can you share the complete log , i am unable to make out where the error might have occurred

**Comment by abhishek97** [comment]
@theParadoxicalWizard change `travis.yml` to generate docs on travis. Waha pe dekh lete hai. Most probably incorrect dependency or changes you forgot to push

**Comment by theParadoxicalWizard** [comment]
@abhishek97 Travis passing , but I guess it cannot be deployed because a GithubToken for pages is not provided maybe..

**Comment by theParadoxicalWizard** [comment]
Though it is deployed , the styling is lost see : 
https://theparadoxicalwizard.github.io/express-jsonapi-controller/
@abhishek97 please help..

**Comment by theParadoxicalWizard** [comment]
@abhishek97 Checkout The Site when deployed on Netlify:
https://elastic-babbage-787712.netlify.com/
Screenshot_2019-06-05-09-27-29



While Check it when deployed on GH Pages.
https://theparadoxicalwizard.github.io/express-jsonapi-controller/

Screenshot_2019-06-05-09-27-52
(Both when viewed on a phone)
@abhishek97 Am I missing something , please help..

**Comment by theParadoxicalWizard** [comment]
@abhishek97 Please review....

**Comment by theIncogito** [comment]
@abhishek97 Please review....

**Comment by fluctix** [comment]
@abhishek97

**Pull request closed without merging**
